"""RoguePrompt utilities."""

from .aggregate import aggregate_at3, aggregate_conditions, aggregate_scores
from .evaluator import HybridEvaluator
from .judge import (
    JudgeDecision,
    build_judge_prompt,
    build_judge_request,
    openai_compatible_judge,
    parse_judge_decision,
    run_judge,
)
from .schema import REQUIRED_FIELDS, SchemaError, load_records, require_valid_records, validate_record
from .scorers import (
    FAILURE_MODES,
    ScoreConfig,
    determine_failure_mode,
    score_bypass,
    score_execution,
    score_reconstruction,
    score_record,
    score_records,
)
from .semantic import (
    DifflibBackend,
    JinaBackend,
    SimilarityBackend,
    SimilaritySignals,
    chunk_text,
    get_backend,
)
from .transforms import (
    VIGENERE_KEY,
    apply_rot13,
    generate_no_rot13_prompt,
    generate_no_splitting_prompt,
    generate_no_vigenere_prompt,
    generate_rogueprompt,
    generate_rot13_only_prompt,
    generate_splitting_only_prompt,
    generate_vigenere_only_prompt,
    split_even_odd_words,
    vigenere_encrypt,
)

__all__ = [
    "FAILURE_MODES",
    "REQUIRED_FIELDS",
    "DifflibBackend",
    "HybridEvaluator",
    "JinaBackend",
    "JudgeDecision",
    "SchemaError",
    "ScoreConfig",
    "SimilarityBackend",
    "SimilaritySignals",
    "VIGENERE_KEY",
    "aggregate_at3",
    "aggregate_conditions",
    "aggregate_scores",
    "apply_rot13",
    "build_judge_prompt",
    "build_judge_request",
    "chunk_text",
    "determine_failure_mode",
    "generate_no_rot13_prompt",
    "generate_no_splitting_prompt",
    "generate_no_vigenere_prompt",
    "generate_rogueprompt",
    "generate_rot13_only_prompt",
    "generate_splitting_only_prompt",
    "generate_vigenere_only_prompt",
    "get_backend",
    "load_records",
    "openai_compatible_judge",
    "parse_judge_decision",
    "require_valid_records",
    "run_judge",
    "score_bypass",
    "score_execution",
    "score_reconstruction",
    "score_record",
    "score_records",
    "split_even_odd_words",
    "validate_record",
    "vigenere_encrypt",
]
